baseurl: "https://adventuresingo.com"
languageCode: "en-us"
title: "Adventures in Go"
theme: "hugo-tania"
paginate: 6

params:
  socialOptions:
    github: https://github.com/chrismgonzalez
    email: chris@cmgsoftwaresolutions.com
    dev-to: https://dev.to/chrismgonzalez

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: Powered by Go

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true