[build]

    publish = "adventuresingo/public"
    command = "hugo --gc --minify"

[build.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_THEME = "repo"

[context.production]
    command = "cd adventuresingo && hugo --gc --themesDir ../.. -b ${URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "cd adventuresingo && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "cd adventuresingo && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"
